version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
  db:
    image: 'mariadb'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: low
      MYSQL_USER: bado
      MYSQL_PASSWORD: badolebado
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
